# Project information
site_name: Continuous Previews
site_description: >-
  Continuous Previews

# Repository
repo_url: https://github.com/UffizziCloud/cpmanifesto
repo_name: UffizziCloud/cpmanifesto

# Styling
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: assets/images/cp-logo.svg
  favicon: assets/images/cp-favicon.png
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - footer.autohide
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate

# Extensions  
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html


# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Page tree
nav:
  - Overview: index.md
  - Developer Stories: developer-stories/developer-stories.md
  - Lessons Learned: lessons-learned/lessons-learned.md
  