services:
  docs:
    build:
      context: https://github.com/gadkins/cpmanifesto:main
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 125M

ingress:
  service: docs
  port: 80

continuous_preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  share_to_github: true
